module.exports = {

    emailInputField: '//input[@id="email"]',
    passwordInputField: '//input[@id="password"]',
    signInButton: '//span[@id="btnSignIn"]',
    profileImage: '(//div[@class="right-column"]//following-sibling::div)[2]',
    loggedInUserEmail: '//span[@id="textInsertionTarget2"]',
    signOut: '//span[text()="Sign Out"]',
    haveAnAccountLoginButton: '//div[@class="login-btn"]',
    loginErrorMessageText: '//p[contains(text(),"Incorrect")]',
    emailPlaceholder: '//span[contains(text(),"EMAIL OR PHONE NUMBER")]',
    passwordPlaceholder: '//span[text()="PASSWORD"]',
    forgotPassword: '//a[text()="Forgot password?"]',
    forgotPasswordPageText:'//p[contains(text(),"Please enter your email")]',
    rememberMeCheckbox: '//input[@id="rememberMe" and @checked="checked" and @name="rememberMe"]',
    passwordResetEmailInputField: '//input[@id="txt_user_emailAddress"]',
    sendButtonPasswordResetPage: '//button[text()="Send"]',
    unregisteredEmailError: '//div[@id="error" and contains(text(),"This email address is not registered")]',
    invalidEmailError: '//div[@id="error" and contains(text(),"This is not a valid email address")]',
    passwordResetSuccessMessage: '//p[contains(text(), "Email sent to")]',
    inlineInsertTextField: '//span[@id="inlineInsertPlaceholderText"]',
    toInputField: '//div[contains(@class,"tags no-suggestion")]',
    typeToInputField: '//div[@class="tags no-suggestion focused"]//input[@type="text"]',
    suggestedPostRecipient: '//div[@class="img-label-list-item"]',
    noteTitleInputField: '//input[@id="noteTitleField"]',
    noteBodyInputField: '//div[@class="ql-editor scroll-enabled"]',
    noteShareButton: '//button[text()="Share"]',
    editButtonPostDetailView: '(//span/button[text()="Edit"])[2]',
    doneButtonPostDetailView: '(//button[contains(text(),"Done")])[1] | (//button[contains(text(),"Done")])[2]',
    postCommentArea: '(//div[@class="dummy-text-area"])[last()]',
    postCommentInputField: '//div[@id="ql-editor-2"]',
    postCommentText: '(//div[@bo-show="!showMore"]/p)[last()]',
    usersSuggestionListInCommentSection: '//ul[@class="rte-autocomplete dropdown-menu dropdown-cont"]/li',
    copyCommentLink: '//a/span[text()="Copy comment link"]',
    copiedToClipboardAlertMessage: '//span[text()="Copied to clipboard"]',
    editCommentLinkPostDetailView: '//a/span[text()="Edit"]',
    editedNowTimestampForComment: '(//a[text()="now"])[2]',
    deleteCommentLinkPostDetailView: '//a/span[text()="Delete"]',
    deleteCommentButton: '//button[text()="Delete"]',
    emoticonIconForCommentPostDetailView: '//div[@class="emoji-popup-btn unselected"]',
    firstEmoticonIcon: '(//div[@title="Grinning face :grinning:"])[1]',
    peopleCategory: `//div[@class='category-label' and contains(text(),'People')]`,
    commentFileUploadPostDetailView: '(//input[@class="comment-file-input"])[last()]',
    fileUploadProgressLine: '//div[@class="progress-line" and @style="width: 100%;"]',
    cancelDeleteCommentButton: '//button[text()="Cancel"]',
    whatsNewIconText: `//a[text()="What's New"]`,
    privateHeadingTextUnderGroupsChannels: '//span[text()="PRIVATE"]',
    createNewGroup:'//div[@class="heading"]/i',
    nextButton:'//button[@class="btn btn-primary" and contains(text(),"Next")]',
    grpName:'//div[@class="form-group"]/input[@placeholder="e.g Marketing"]',
    nextButtonForGrpCreation: '//button[@id="crtGrpNxtBtn"]',
    createGroup:'//button[@class="btn btn-primary" and contains(text(),"Create group")]',
    privateGroup: '//div[@class="group-create-type"]//div/div/div[contains(text(),"Private")]',
    deleteGroup: '//span[contains(text(),"Delete group")]',
    deleteButton: '//button[contains(text(),"Delete")]',
    myFeed: '//li/a[contains(text(),"My feed")]',
    editButton: '(//span/button[text()="Edit"])[2]',
    pinContentToTopOfgrpList: '//li//span[contains(text(),"Pin content to the top of this group")]',
    linkTo: '//input[@name="url"]',
    pinToGrp: '//button[contains(text(),"Pin to group")]',
    removeLink:'//div[@class="edit-remove-link"]/a[contains(text(),"Remove")]',
    saveChanges: '//button[@class="btn btn-primary" and contains(text(),"Save Changes")]',
    pinToTopOfgrpList: '//li//span[contains(text(),"Pin to top of my group list")]',
    unpinToTopofgrpList: '//li//span[contains(text(),"Unpin from top of my group list")]',
    seeMorePrivate: '//li[@bo-show="privateGroupsCollapsed && privateGroupsArray && privateGroupsArray.models.length > 5"]/a | //li[@bo-show="privateGroupsCollapsed && privateGroupsArray && privateGroupsArray.length > 5"]/a',
    closeIcon: '//button[@class="close"]',
    feedSearchInputField: '//input[@id="feed_search_input"]',
    searchIcon: '//*[@id="feed_search_bar"]/form/div[2]/i[1]',
    pollIcon: '//*[@id="poll-icon" and @class="icon_poll-gray"]',
    pollwithImages: '//li[contains(text(),"Poll with Images")]',
    attachment: '//cnv-poll//input[@class="file-input ng-hide"]',
    pollDeletePost: '//span[text()="Delete post"]',
    pollwithText: '//li[contains(text(),"Poll with Text")]',
    pollColorIcon:'//*[@id="poll-icon" and @class="icon_poll-blue"]',
    progressBar: '//div[@class="internal-wrapper"]//div[@class="progress-bar"]',
    option1: '//*[@id="txt_0"]',
    option2: '//*[@id="txt_1"]',
    addNewChoice: '//span[contains(text(),"Add a new choice")]',
    locationIcon: '//*[@id="location-icon"]',
    pollEnds:'//*[@id="poll_ends_container"]/label',
    calendarIcon:'//*[@id="poll_ends_container"]/span[@class="poll-calendar"]/span[1]/i',
    hoursIcon:'//*[@id="hrs-label"]',
    mintsIcon:'//*[@id="mins-label"]',
    peopleWhoVotedForThis: '//div[@class="modal-header"]/h4[contains(text(),"People who voted for this")]',
    closeButton: '//button[@class="close"]',
    closeLocationIcon: '//div[@class="location-container"]/div[@class="close-btn"]/i',
    locationIconBlueColor: '//*[@id="location-icon" and @class="icons_Location-blue"] | //div[@class="add-location-blue"]',
    editButtonInPostDetailView:'(//span/button[text()="Edit"])[2]',
    locationIconInDetailView: '//*[@id="location-icon-editor"]',
    doneButtonInPostDetailView: '(//button[contains(text(),"Done")])[1] | (//button[contains(text(),"Done")])[2]',
    more: '(//a/span[contains(text(),"More")])[1]',
    viewRevisions: '(//a[contains(text(),"View revisions")])[1]',
    closeButtonInDetailView: '//div[@class="close-btn"]/i',
    textToDisplay: '//input[@name="resource_name"]',
    gifIcon: '//div[@id="iShowGiphyPopup"]',
    firstGifImage: '(//img[@class="lazy"])[1]',
    firstGifUploadedVerification: '(//img[@class="file-converted"])[1]',
    createTagIcon: '//div[@class="icon_tag-01-01-darkgray" or @class="icon_tag-01-01-darkgray-old"]',
    startTypingText: '//a[text()="start typing..."]',
    tagInputField: '//a[text()="start typing..."]/following-sibling::*[1]',
    richTextFormatIcon: '//div[@class="editor-toolbar texttoolbar-darkgray"]',
    boldIcon: '//div[@id="inline-insert-toolbar"]//span[@class="ql-format-group"]//span[@class="ql-format-button ql-bold icons3_Bold-darkgray"]',
    bulletPoints: '//span[@class="ql-format-button ql-bullet orderedlist-darkgray"] ',
    colorPickerIcon: '//span[@class="ql-picker-label"]',
    redColorTextBox: '//span[@data-value="#ed462e"]',
    colorProperty: '//span[@style="color: rgb(237, 70, 46);"]',
    crossedTextFormatting: '//span[@class="ql-format-button ql-strike strikethrough-darkgray"]',
    savedInDrafts: '//label[text()="Saved in Drafts"]',
    draftsLink: '//a[text()="Drafts"]',
    emoticonIcon: '//div[@class="emoji-popup-btn unselected"]',
    selectingEmoji:'//li[@class="emoji-category"]/div[@class="category-label" and contains(text(),"People")]/../ul[@class="emoji-list"]//div[@title="Grinning face :grinning:"]',
    italicIcon: '//span[@class="ql-format-button ql-italic italic-darkgray"]',
    underlineIcon: '//span[@class="ql-format-button ql-underline underline-darkgray"]',
    addCommentsThumbnail: '//div[@id="ql-editor-1"]',
    numberFormatIcon: '//span[@class="ql-format-button ql-list numberedlist-darkgray"]',
    textforSerialPoints: '//div[@id="ql-editor-1"]',
    div_Button:'//div[@class="editor-toolbar texttoolbar-darkgray"]',
    spanInsertLinkButton: '//span[contains(@class,"ql-inline-link")]',
    inputUrl: '//input[@name="url"]',
    textToDisplay:'//input[@name="resource_name"]',
    insertButton: '//button[@type="submit"]',
    fileUploadForFeed: '//div[@class="icons2_Attach-darkgray attachIconInlineInsert"]/input[@name="file"]',
    imageFileUploadVerification: '//img[@class="file-converted"]',
    companyLogo: '//a[contains(@class,"convo-logo")]//img',
    privacyButton: '//a[text()="Privacy"]',
    securityButton: '//a[text()="Security"]',
    gdprButton: '//a[text()="GDPR"]',
    termsButton: '//a[text()="Terms of Service"]',
    permissionLinkInMoreMenuBar: '(//a[text()="Permissions"])[1]',
    commentOnlyFromPermissionsContextMenu: '(//span[text()="Comment only"])[1]',
    permissionsUpdatedSuccessMessage: '//span[text()="Permissions updated"]',
    tickMarkWithCanCommentOnlyPermission: '(//li/a/span[contains(text(),"Comment only")])[1]/..//i[@class="cnv-icons-12 icon-cnv-tick"]',
    viewOnlyFromPermissionsContextMenu: '(//span[text()="View only"])[1]',
    addTagsButtonInPostDetailView: '//div[text()="Add tags"]',
    tagInputField: '//div[@class="tags focused"]/input',
    doneButtonOnTagPost: '//div[@class="modal-footer"]/button[contains(text(),"Done")]',
    anchorLinkClicked: '(//div[@class="tags"]/a)[5]',
    addTagInputField: '//a[@class="add-more-placeholder" and contains(text(),"start")]/../input',
    removeTag: '//div/a[@class="remove-button icons2_Close-lightgray"]',
    postEditorInPostDetailView: '//div[@class="ql-editor" and @contenteditable="true"]',
    autoSavedText: '(//span[contains(text(),"Autosaved")])[1]',
    likeButtonInPostDetailView: '//div[text()="Like"]',
    unlikeButton: '//div[contains(text(),"Unlike")]',
    addTag: '//a[@class="add-more-placeholder" and contains(text(),"start")]',
    muteThisPost: '(//a[text()="Mute this post"])[1]',
    mutedAlertMessage : '//span[contains(text(),"Muted")]',
    hidePanel: '//div[@class="format-label" and contains(text(),"Hide panel")]',
    showPanel: '//div[@class="format-label" and contains(text(),"Show panel")]',
    starPostInDetailView: '//div[contains(text(),"Star post")]',
    UnstarPostInDetailView: '//div[contains(text(),"Unstar post")]',
    publicGroups: '//span[text()="PUBLIC"]/../following-sibling::li//a',
    openPostLinkInPostContextMenu: '//a/span[text()="Open post"]',
    uploadLinkInPostDetailView: '//a[text()="Upload"]',
    editPostLinkInPostContextMenu: '//a/span[text()="Edit post"]',
    editPostLinkDisabledInPostContextMenu: `//a[contains(@class,'disabled')]/span[text()="Edit post"]`,
    doneButtonInPostDetailView: '(//button[text()="Done"])[1]',
    editButtonInPostDetailView: '(//button[text()="Edit"])[2]',
    permissionsLinkInPostContextMenu: '//a/span[text()="Permissions"]',
    canEditAndCommentLinkInPostContextMenu: '//a/span[text()="Can edit and comment"]',
    permissionsUpdatedSuccessMessage: '//span[text()="Permissions updated"]',
    commentOnlyLinkInPostContextMenu: '//a/span[text()="Comment only"]',
    viewOnlyLinkInPostContextMenu: '//a/span[text()="View only"]',
    muteNotificationsLinkInPostContextMenu: '//a/span[text()="Mute notifications"]',
    postMuteIcon: '//div[@class="action-items-wrapper"]/i',
    unmuteNotificationsLinkInPostContextMenu: '//a/span[text()="Unmute notifications"]',
    addTagsLinkInPostContextMenu: '//a/span[text()="Add tags"]',
    tagInputFieldInTagThisPostModal: '//div[@class="modal-body sharepost"]//a[contains(text(),"+Add more")]/..//input',
    doneButtonInTagThisPostModal: '//button[contains(text(),"Done")]',
    startThisPostLinkInPostContextMenu: '//a/span[text()="Star this post"]',
    unstarThisPostLinkInPostContextMenu: '//a/span[text()="Unstar this post"]',
    networkLogo: '(//img[@bo-src="networkLogo"])[last()]',
    profileImageDropdown: '//div[@class="right-column"]/div/cnv-dropdowns/span/a/i',
    editProfileLink: '//span[text()="Edit profile"]',
    aboutMeHeadingUserProfileView: '//h2[text()="About Me"]',
    cancelButtonUserProfileView: '//button[text()="Cancel"]',
    fixitLinkUserFeedView: '//a[text()="Fix it"]',
    userProfilePhoneField: '//span[text()="Add phone no. with country code" and @class="input-text-label-content"]',
    userProfilePhoneInputField: '//span/i[@class="action_icon cnv-icons-20 icons_Phone-darkgray"]/../following-sibling::input',
    userProfileLocationField: '//span[text()="Add your location" and @class="input-text-label-content"]',
    userProfileLocationInputField: '//span/i[@class="action_icon cnv-icons-20 icons_Location-darkgray"]/../following-sibling::input',
    userProfileLinkedinField: '//span[text()="linkedin.com/pub/user" and @class="input-text-label-content"]',
    userProfileLinkedinInputField: '//span/i[@class="action_icon cnv-icons-20 linkedin-darkgray"]/../following-sibling::input',
    userProfileTwitterField: '//span[text()="twitter.com/user" and @class="input-text-label-content"]',
    userProfileTwitterInputField: '//span/i[@class="action_icon cnv-icons-20 twitter-darkgray"]/../following-sibling::input',
    userProfileSaveButton: '//button[text()="Save"]',
    editProfileButton: '//button[text()="Edit Profile"]',
    userProfilePhoneFieldWithValue: '//div[@class="profile-details"]/span[contains(@ng-if,"phone")]/span/span',
    userProfileLocationFieldWithValue: '//div[@class="profile-details"]/span[contains(@ng-if,"location")]/span',
    userProfileLinkedinFieldWithValue: '//span[contains(@ng-if,"linkedin")]/a',
    userProfileTwitterFieldWithValue: '//span[contains(@ng-if,"twitter")]/a',
    topGroupsUserFeedView: `//div[@bo-show="topGroups"]/ul/li/a`,
    userProfilePhoneFieldFilledWithValue: '//p/strong[text()="Phone: "]/following-sibling::span[@ng-class="textLabelContentClass"]',
    userProfileLocationFieldFilledWithValue: '//p/strong[text()="Location: "]/following-sibling::span[@ng-class="textLabelContentClass"]',
    userProfileLinkedinFieldFilledWithValue: '//p/strong[text()="LinkedIn: "]/following-sibling::span[@ng-class="textLabelContentClass"]',
    userProfileTwitterFieldFilledWithValue: '//p/strong[text()="Twitter: "]/following-sibling::span[@ng-class="textLabelContentClass"]',
    userProfileViewAddPhoneNumber: '//span[text()="Add Phone Number"]',
    userFeedViewProfileImage: '//cnv-user-profile-image[@profile="true"]',
    userFeedViewProfileImageUpdateLink: '//div[@ng-click="openProfilePictureModal()" and contains(text(),"Update")]',
    userFeedViewProfileImageUploadInputField: '//input[@id="combinedProfileUploadInput"]',
    applyPhotoButton: '//button[text()="Apply Photo"]',
    applyPhotoGeneratingThumbnails: '//div[text()="Generating thumbnails..."]',
    profilePictureUploadSuccess: '//div[@class="cnv-note-gallery-container"]/div/ul/li/i[text()="1 new"]',
    userProfileViewUploadPicture: '//div[text()="Upload" and @ng-click="openProfilePictureModal()"]',
    feedFileUploadInputField: `//div[@class='icons2_Attach-darkgray attachIconInlineInsert']/input[@name='file']`,
    fileUploadAndConversionSuccess: `//img[@class='file-converted']`,
    galleryViewElipses: `//a[@id='opts-menu']/span`,
    galleryViewElipsesCopyLink: `//li/a[contains(@ng-click, 'promptCopyLink()')]`,
    greenChatActiveIcon: `//span[text()='Chats']/../div/div[@class='listUserStatusOnline']`,
    chatSearchInputField: `//input[@placeholder='SEARCH']`,
    searchedChatUserSuggestion: `//div[@id='chatsView']//div[@class='listUserName']`,
    firstChatWindowInputField: `//div[@id='ql-editor-1']`,
    progressBar: '//div[@class="progress-bar ng-hide"]',
    progressBar2: '(//div[@class="progress-bar ng-hide"])[2]',
    disabledShareButton: '//button[@disabled="disabled" and text()="Share"]',
    rectangleTool: `//div[@class='row galleryHeaderContainer']/ul/li[@title='Rectangle']/a`,
    galleryViewImageCanvasArea: `//canvas[@id="img-drawing-canvas"]`,
    commentOnThisTooltip: `//span[contains(text(),'Comment on this')]`,
    snippetCommentInputField: `(//div[@class='row comment-editor-container']//div/div//div[@class='feed-comment-editor-active-cont edit-mode']//cnv-editor/div/div)[1]`,
    editorText: '//div[@class="ql-editor"]/div',
    commentOnThisPopup: '//span[text()="Comment on this"]',
    imageUploadinput: '//div[@class="notesAppContainer note-container"]/input',
    deleteImage: '//span/a[contains(text(),"Delete")]',
    deleteButtonForFile: '//button[contains(text(),"Delete")]',
    shareThis: '//div[@class="format-label" and contains(text(),"Share this")]',
    peopleandGroupInput: '(.//*[normalize-space(text()) and normalize-space(.)="+Add more"])[1]/following::input[1]',
    publish: '//button[contains(text(),"Publish")]',
    shared: '//span[contains(text(),"Shared")]',
    deletePost: '(//a[text()="Delete post"])[1]',
    movedtoTrash: '//span[contains(text(),"Moved to trash")]',
    restore : '//button[contains(text(),"Restore")]',
    restored: '//span[contains(text(),"Restored")]',
    deleteforever: '//button[contains(text(),"Delete forever")]',
    deleted: '//span[contains(text(),"Deleted")]',
    deletePostLinkInPostContextMenu: '//a/span[text()="Delete post"]',
    trashFeed: '//a[contains(text(),"Trash")]',
    mentions: '//a[contains(text(),"Mentions")]',
    deletePermanently: '//span[contains(text(),"Delete permanently")]',
    restorePost: '//span[contains(text(),"Restore post")]',
    starThisPost: '//a/span[text()="Star this post"]',
    starred: '//a[contains(text(),"Starred")]',
    acknowledgmentCheckbox: '(.//*[normalize-space(text()) and normalize-space(.)="Recipients must acknowledge to view the post (Beta)"])[1]/preceding::label[1]',
    signOutDropdown: '//a[@class="dropdown-toggle"]/i[@class="cnv-icons-14 icons2_Dropdown-c2c2c2-png" or @class="cnv-icons-16 icons2_Dropdown-c2c2c2-png"]',
    haveanAccount: '//span[contains(text(),"Log in")]',
    copyLink: '//li//span[contains(text(),"Copy link")]',
    checkBoxForAck: '//input[@name="ackPostChkbox" and @class="cnv-checkbox ack-checkbox ng-pristine ng-untouched ng-valid ng-empty"]',
    editPostLink: '//a/span[text()="Edit post"]',
    muteNotifications: '//a/span[text()="Mute notifications"]',
    crossButton: '//button[@class="close view-close"]',
    inputField: '//input[@class="input ng-pristine ng-valid ng-empty ng-touched"]',
    suggestionList: '//li[@class="suggestion-item selected"]',
    invitationCross: '//span[@class="cross"]',
    bellIcon: '//span[@class="bell-hit-area"]',
    latestActivity: '//span[contains(text(),"Sort: Latest activity")]',
    latestActivityDropdown: '(//span[contains(text(),"Sort: Latest activity")]/../i)[1]',
    latestPost: '//ul/li[contains(text(),"Latest post")]',
    postEditor: '//div[@class="ql-editor" and @contenteditable="true"]',
    latestPostFilter: '//span[contains(text(),"Sort: Latest post")]',
    linkPostCommentInputField: `//div[@class='ql-editor scroll-enabled']`,
    commentSectionProgressbar: `//div[contains(@class,'comments')]//div[@class='progress-bar']`,
    displayedFileTextInGalleryView: `//div[@class='textLayer']/div`,
    fullscreenIconInGalleryView: `//div[@class='row galleryHeaderContainer']//ul//li[@title='Full Screen']`,
    fitToScreenButtonGalleryInGalleryView: `//button[contains(text(),'Fit to screen')]`,
    galleryViewElipsesDeleteLink: `//li/a[contains(@ng-click, 'deleteFile')]`,
    deleteButtonForFileInGalleryView: `//div[@class='modal-footer']/button[contains(text(),'Delete')]`,
    galleryViewLikeButton: `//div[@class='segment pull-right gallery-header']//ul/li/div[contains(text(),'Like')]`,
    galleryViewUnlikeButton: `//div[@class='segment pull-right gallery-header']//ul/li/div[contains(text(),'Unlike')]`,
    galleryViewGoToPostIcon: `//a[@class='goto-post']/span`,
    galleryViewNextButton: `//a[@title='Next']/span`,
    galleryViewPreviousButton: `//a[@title='Previous']/span`,
    galleryViewColorRectangleIcon: `//div[@class='row galleryHeaderContainer']/ul/li[@class='color-picker dropdown dropdown-toggle']`,
    galleryViewGreenColorForColorRectangle: `//ul[contains(@class, 'color-picker')]/li[@class='green']`,
    galleryViewArrowIcon: `//li[@class='toolbox dropdown dropdown-toggle']/a[@title='Arrow']`,
    galleryViewDownloadIcon: `//li[@class='download']/a/span`,
    videoPlaybackTime: `//div[@class='time']`,
    galleryViewZoomIcon: `//div[@class='row galleryHeaderContainer']/ul//li/a[@title='Zoom']`,
    galleryViewZoomPercentageInputField: `//span[@class='zoom-percent-container']/input`,
    galleryViewZoomMetrics: `//div[@class='panzoom']`,
    deleteCommentLink: `//a/span[text()="Delete"]`,
    firstChatWindowCrossButton: `//div[@class='btnClose']/i[contains(@class,'white')]`,
    secondChatWindow: `//div[2]/div[@class='namesPopover']`,
    galleryViewExitFullScreenIcon: `//a[@title='Exit fullscreen']`,
    editCommentLink: `//span[contains(text(),'Edit')]`,
    copyCommentLink: `//span[contains(text(),'Copy comment link')]`,
    feedSearchDropdownIcon: `(//div[@class='dropdown-ico-wrapper']/i[@title='Show search options'])[1]`,
    feedSearchFilters: `//div[@class='bar-wrapper expand-bar-static' or @class='bar-wrapper expand-bar-static']`,
    feedViewFeedItemsCount: `//cnv-feed/div/cnv-feed-item`,
    feedViewAttachedFilesCount: `//cnv-feed-item[@hasfiles='true']`,
    feedViewAttachedAudioFilesCount: `//cnv-feed-item[@hasfiles='true']//cnv-audio-player//audio`,
    feedViewAttachedExcelFilesCount: `//cnv-feed-item[@hasfiles='true']//i[contains(@class,'xls')]`,
    feedViewAttachedImageFilesCount: `//cnv-feed-item[@hasfiles='true']//img[@class='feedReelImage']`,
    feedViewAttachedPdfFilesCount: `//cnv-feed-item[@hasfiles='true']//i[contains(@class,'pdf')]`,
    feedViewAttachedPptFilesCount: `//cnv-feed-item[@hasfiles='true']//i[contains(@class,'ppt')]`,
    feedViewAttachedVideoFilesCount: `//cnv-feed-item[@hasfiles='true']//a/div//video`,
    feedViewAttachedWordDocsFilesCount: `//cnv-feed-item[@hasfiles='true']//i[contains(@class,'doc')]`,
    feedViewChatItemsCount: `//cnv-feed-item//div/a[contains(text(),'Chat view details')]`,
    feedViewLinkFeedItemsCount: `//cnv-feed-item//div[@class='link-feed-description']/span`,
    feedViewMessageFeedItemsCount: `//div[@class='note']`,
    firstPrivateGroup: `(//ul/li[contains(@bo-repeat, 'privateGroupsArray')]/div/a)[1]`,
    secondPrivateGroup: `(//ul/li[contains(@bo-repeat, 'privateGroupsArray')]/div/a)[2]`,
    feedFilterFromDropdown: `(//span[contains(text(),'From: Anyone')]/../i)[1]`,
    feedFilterToDropdown: `(//span[contains(text(),'To: Anyone')]/../i)[1]`,
    statusNoFeedToDisplay: `//div[@class='feed_load_status' and text()='There is no feed to display.']`,
    activeChatExpandIconP2PChat: `//a[@bo-mouseup='openChatInFullView()']`,
    expandSettingsButton: `//div[contains(@class,'expandSettingsBtn')]/i`,
    chatListExpandIcon: `//div[contains(@class,'chatUserListHeader')]/a`,
    p2pChatSettingsGearIcon: `//cnv-dropdowns[@cnv-dropdown-ctrl='chatOptions']/span`,
    p2pMuteChatSetting: `//span[text()='Mute chat']`,
    p2pUnMuteChatSetting: `//span[text()='Unmute chat']`,
    chatListSettingsGearIcon: `//cnv-dropdowns[@cnv-dropdown-ctrl='chatSettingsOptions']/span/a`,
    userStatusBusyLink: `//a/span[text()='Busy']`,
    userStatusAvailableLink: `//a/span[text()='Available']`,
    userStatusBusy: `//div[@class='listUserStatusBusy']`,
    userStatusAvailable: `//div[@class='listUserStatusOnline']`,
    p2pAddToChatIcon: `//div[@class='addToChat']/i[1]`,
    secondChatWindowInputField: `//div[@id='ql-editor-2']`,
    groupChatFileInputField: `//div[@class='messageInputContainer']//input[@class='inputHide']`,
    sharedGifImage: `//div/img[contains(@bo-if,'GIF')]`,
    gifIconInChatWindow: `//div[@class='giphy-action-container']//div[@class='attachmentButton giphy']`,
    groupChatSettingsGearIcon: `//cnv-dropdowns[@cnv-dropdown-ctrl='chatOptions']/span`,
    groupChatRenameDoneButton: `//button[text()='Done']`,
    renameGroup: `//a/span[text()='Rename group']`,
    renameGroupChatInputField: `//div[@bo-if='editChatTitle']/input`,
    shareThisChat: `//a/span[text()='Share this chat']`,
    leaveChat: `//a/span[text()='Leave chat']`,
    leaveChatYesButton: `//button[contains(text(),'Yes')]`,
    chatLeftMessage: `//div[@class='invite-left-msg']/span`,
    createNewChatIcon: `//div[@class='create-new-chat-btn']/i`,
    signupNowLink: `//*[@id="body"]/div/div[2]/div[5]/p[4]/a`,
    signupEmailInputField: `//*[@id="signup"]/div/div[2]/input`,
    signupButton: `//*[@id="signup"]/div/div[4]/button`,
    yahooSigninButton: `//span[text()='Sign in']`,
    yahooUsernameInputField: `//input[@id='login-username']`,
    yahooSigninNextButton: `//input[@id='login-signin']`,
    yahooPasswordInputField: `//input[@id='login-passwd']`,
    yahooPasswordNextButton: `//button[@id='login-signin']`,
    yahooHomeButton: `//a/span[text()='Home']`,
    verificationCodeInputField: `//*[@id="verificationCodeInput"]`,
    verifyButton: `//*[@id="verificationCodeBtn"]`,
    clickHereLinkToResendVerficationCodeEmail: `//div[@id='emailVerification']//span[text()='click here']`,
    signupFirstNameInputField: `//input[@placeholder='First Name' and @style]`,
    signupLastNameInputField: `//input[@placeholder='Last Name' and @style]`,
    signupJobTitleInputField: `//input[@placeholder='Job Title' and @style]`,
    signupPasswordInputField: `//input[@type='password'and @style]`,
    signupNextButton: `//input[@placeholder='First Name' and @style]/../following-sibling::div/button`,
    signupSkipThisForNowProfilePictureLink: `//span[contains(@class,'skip-photo')]`,
    signupSkipThisForNowGroupCreationLink: `//div[@id='skipGroupCreation']/span`,
    signupGetStartedLink: `//*[@id="inviteUsersSubModeWelcomeToNetwork"]/div[4]/div/div[1]/div[8]/span`,
    signupCompletionScreenCrossIcon: `//div[@class='cross']/i`,
    signupClickHereLink: `//a[contains(text(),'Click here')]`,
    signupConvoGettingStartedPlaylistPost: `//div[@class='title-text']/a[contains(text(),'Convo Getting Started Playlist')]`,
    signupPolicyAcceptButton: `//button[contains(text(),'Accept')]`,
    userMenuDropdown: `//cnv-dropdowns[contains(@class,'user-menu-dropdown')]/span/a/i`,
    userMenuSignoutLink: `//span[text()='Sign Out']`,
    loginButtonOnSignoutPage: `//div[@class='login-btn']/span`,
    signupProfilePictureUploadInputField: `//input[@class='chooseFile_SelectImage Orginal']`,
    signupApplyPhotoButton: `//*[@id="photo-crop"]/div[2]/div[2]/button[2]`,
    signupNextButtonAfterProfilePhotoUploaded: `//*[@id="uploadProfilePic"]/div[3]/div[2]/div/div[1]/div/button`,
    signupGroupNameInputField: `//*[@id="setupTeamView"]/div[3]/div[1]/div[2]/div[1]/input`,
    signupCreateGroupButton: `//*[@id="setupTeamView"]/div[3]/div[2]/button`,
    signupStartUsingConvoButton: `//div[@id='inviteUsersSubModeWelcomeToNetwork']//button[contains(text(),'Start Using Convo!')]`,
    editProfileCancelButton: `//button[text()='Cancel']`,
    signupPublicGroupLabel: `//label[@for='public']`,
    signupInviteTeammatesFirstInputField: `//*[@id="inviteUsersSubModeWelcomeToNetwork"]/div[4]/div/div[1]/div[1]/input`,
    addGroupIcon: `//i[contains(@ng-click,'createGroup();')]`,
    groupTypePrivateGroup: `//div[text()='Private']`,
    groupCreationNextButton: `//button[text()='Next']`,
    groupNameInputField: `//input[contains(@class,'group-name')]`,
    createGroupButton: `//button[text()='Create group']`,
    elipsesInGroupView: `//cnv-dropdowns[contains(@cnv-dropdown-ctrl,'groupDropdown')]/span/a/i`,
    groupSettingsInGroupViewElipsesMenu: `//a/span[text()='Group settings']`,
    checkboxShareLocationWithPostContentAutomaticallyInGroupSettings: `//span[text()='Share location with post content automatically']/../label`,
    saveChangesButtonInGroupSettings: `//button[text()='Save Changes']`,
    settingsSavedSuccessMessage: `//span[text()='Your settings have been saved.']`,
    geoLocationAddressInInlineInsert: `//p[@class='geo-location' and text()='at ']/span`,
    geoLocationAddressInCreatedPost: `(//p[@class='geo-location']/span)[2]`,
    listOfPrivateGroups: `//li[contains(@bo-repeat,'group in privateGroupsArray')]/div/a`,
    acknowledgePostCheckbox: `//label[@for='ackPostChkbox']`,
    crossIconForRecipientGroupInInlineInsert: `//a[contains(@class,'remove-button')]`,
    geoLocationCrossIconInEditPost: `//div[contains(@class,'location-container-editor')]/div/i`,
    disabledGeolocationIconInEditPost: `//div[@id='location-icon-editor' and contains(@class,'disabled')]`,
    networkDropdown: `//div[@class='network-logo-wrapper']/cnv-dropdowns[@class='hidden-xs header-dropdown']/span/a/i`,
    networkSettingsLinkInNetworkDropdown: `//span[contains(text(),'Network settings')]`,
    feedAndSharingLink: `//a[contains(text(),'Feed and sharing')]`,
    feedAndSharingToField: `(.//*[normalize-space(text()) and normalize-space(.)='To:'])[1]/following::a[1] `,
    feedAndSharingToInputField: `(.//*[normalize-space(text()) and normalize-space(.)='To:'])[1]/following::input[1]`,
    postContextMenuShareWithOthersLink: `//span[contains(text(),'Share with others')]`,
    shareWithOthersInputField2: `(.//*[normalize-space(text()) and normalize-space(.)='+Add more'])[1]/following::input[1]`,
    updatingSharingInfoSuccessMessage: `//span[text()='Updating sharing info']`,
    invitePeopleToThisGroupInGroupViewElipsesMenu: `//a/span[text()='Invite people to this group']`,
    inviteTeammatesSearchPlaceholderLink: `//a[text()='Search']`,
    inviteTeammatesSearchInputField: `//a[text()='Search']/following-sibling::input`,
    inviteButton: `//div/button[text()='Invite']`,
    invitationSentMessage: `//div[text()='Invitation sent!']`,
    invitationSentMessageCrossIcon: `//div[text()='Invitation sent!']/../../span`,
    cancelButton: `//button[text()='Cancel']`,
    groupEmail: `//span[text()='Group email']/following-sibling::a`,
    composeButtonYahooMail: `//a[text()='Compose']`,
    messageToFieldYahooMail: `//input[@id='message-to-field']`,
    messageSubjectFieldYahooMail: `//input[@data-test-id='compose-subject']`,
    messageBodyFieldYahooMail: `//div[@data-test-id='rte']`,
    sendButtonYahooEmail: `//button/span[text()='Send']`,
    messageSentSuccessMessageYahooMail: `//span[contains(text(),'Your')]/a/..`,
    locationIconInInlineInsert: `//cnv-insert-add-item-options/div[@id='location-icon']`,
    locationIconInEditPost: `//div[@id='location-icon-editor']`,
    geoLocationAddressInPostEditView: `//p[@class='geo-location' and text()='at ']/span`,
    everyoneGroupCrossIcon: `//span[text()='Everyone']/..//div`,
    postInFeedView: `//div[@class='note']`,
    feedBody: `//div[@id='home-center-panel']`,
    newPostsBanner: `//div[@id='feed-updates-available-notif']/div/span`,
    editedNowTimestampForPost: `//span[@class='nowrap']//a[text()='now']`,
    postTextInPostDetailsView: `//div[@class='ql-editor']/div`,
    canEditAndCommentLinkInPostDetailView: `//li[@class='more-options']//a/span[text()='Can edit and comment']`,
    canEditAndCommentLinkInPostDetailViewSelected: `//li[@class='more-options']//a/span[text()='Can edit and comment']/../i[contains(@class,'icon-cnv-tick-white')]`,
    commentOnlyLinkInPostDetailView: `//li[@class='more-options']//a/span[text()='Comment only']`,
    thisPostIsClosedForEditingText: `//div/span[text()='This post is closed for editing.']`,
    viewOnlyLinkInPostDetailView: `//li[@class='more-options']//a/span[text()='View only']`,
    commentsAreClosedForThisPostText: `//div/div/cnv-comment-editor//span[contains(text(),'Comments are closed for this post')]`,
    teamDirectory: `//a/span[text()='Team directory']`,
    everyoneGroupNameHeadingInTeamDirectory: `//div/a[contains(text(),'Everyone (')]`,
    manageUsersLinkInNetworkSettings: `//li/a[text()='Manage users']`,
    limitNetworkUsersInputField: `//input[@id='networkCapLimit']`,
    settingsSavedSuccessMessageInNetworkSettings: `//span[text()='Settings Saved']`,
    inviteTeammatesInputFieldInTeamDirectory: `//div[@class='inv-teammates']/input`,
    userCapLimitReachedMessage: `//span[contains(text(),'reached the user cap')]`,
    applyNetworkCapButton: `//button[text()='Apply network cap']`,
    networkNameInputField: `//input[@id='networkName']`,
    networkInformationHeading: `//div[@class='header' and text()='Network information']`,
    settingsSavedSuccessMessageInNetworkInformation: `//span[text()='Your settings have been saved']`,
    networkImageUploadInputField: `//input[@id='networkImageUpload']`,
    networkImageUploadSpinner: `//span[@class='cnv-spinner light']`,
    networkImageURL: `//div/img[@bo-src='accountImageUrl']`,
    setUserPrivileges: `//li[text()='Set user privileges']`,
    blockUsersInputField: `//input[@placeholder='Add email, domain or phone number']`,
    blockButtonInNetworkSettings: `//button[text()='Block']`,
    firstPrivateGroupInGroupsList: `(//i[contains(@class,'privateGroup')]/following-sibling::a)[1]`,
    inviteButtonInGroupView: `//form/button[text()='Invite']`,
    inviteBlockedMessage: `//span[contains(text(),'is blocked. Contact your network admin to invite blocked users.')]`,
    inviteBlockedMessageCrossIcon: `//span[contains(text(),'is blocked. Contact your network admin to invite blocked users.')]/../span/i`,
    settingsSavedSuccessMessageInUserPrivileges: `//span[text()='Settings saved']`,
    enterAdminModeLink: `//span[text()='Enter admin mode']`,
    closeGallery: `//a[@title='Close Gallery']`,
    notificationPreferences: `//span[text()='Notification preferences']`,
    myAccountLink: `//a[contains(text(),'My account')]`,
    newLoginEmailInputField: `//input[@id='newEmail']`,
    changeEmailButton: `//button[@id='emailBtn']`,
    emailAddressUpdatedSuccessMessage: `//span[text()='Email address updated.']`,
    currentPasswordInputField: `//input[@id='curPass']`,
    newPasswordInputField: `//input[@id='newPass']`,
    passwordUpdatedSuccessMessage: `//span[text()='Password updated.']`,
    changePasswordButton: `//button[normalize-space()='Change password' and contains(@class,'disabled') = 0]`,
    signOutAllOtherSessions: `//button[text()='Sign out all other sessions']`,
    welcomeTitleForNewNetwork: `//div[contains(@class,'title') and contains(text(),'Welcome to the')]`,
    clickHereToResendLink: `//div[@id='emailVerification']//a`,
    disableMyAccountLink: `//a[text()='Disable my account']`,
    disableAccountButton: `//button[text()='Disable Account']`,
    verificationCodeSentSuccessMessage: `//div[@class='verificationEmailSuccessful']`,
    upgradeNowButton: `//a[text()='Upgrade Now']/../../..//i`,
    postPermissionOptionsDropdown: `//div[@class='post-permission-options']//i`,
    canEditAndCommentsLinkInInlineInsertDropdown: `//a/span[text()='Can edit and comments']`,
    commentOnlyLinkInInlineInsertDropdown: `//a/span[text()='Comment only']`,
    viewOnlyLinkInInlineInsertDropdown: `//a/span[text()='View only']`,
    canEditAndCommentsPermissionSelected: `//a/span[text()='Can edit and comments']/../i`,
    commentOnlyPermissionSelected: `//a/span[text()='Comment only']/../i`,
    viewOnlyPermissionSelected: `//a/span[text()='View only']/../i`,
    enableSharingLinkInInlineInsertDropdown: `//a/span[text()='Enable Sharing']`,
    enableSharingPermissionSelected: `//a/span[text()='Enable Sharing']/../i`,
    commentEditorAreaInPostDetailView: `//div[@class='row comment-editor-container']//div[text()='Add a comment...']`,
    shareWithOthersInputLink: `//div[@class='tags']`,
    shareWithOthersInputField: `//div[@class='tags']/input`,
    postRecipientFieldInEditPostView: `//span[@id='tags-container']/tags-input/div/div/div`,
    enableSharingLinkUnderPermissionsMenuInPostDetailedView: `//a/span[text()='Enable sharing']`,
    commentSectionDisabledFurtherSharingMessage: `//span[contains(text(),'Post creator has disabled further sharing')]`,
    editPostSectionDisabledFurtherSharingMessage: `//span[contains(@class, 'tags-meta-right sharing-disabled-label')]`,
    groupNameHeading: `//span[@id='feed_title']/strong/span`,
    inviteToGroupInputLink: `//form[@name='inviteUserToGroup']//div[@class='tags']`,
    inviteToGroupInputField: `//form[@name='inviteUserToGroup']//div[@class='tags focused']/input`,
    inviteToGroupInvitationSuccessMessage: `//span[contains(text(),'Your invitation has been sent to')]`,
    inviteToGroupInvitationSuccessMessageCrossIcon: `//span[contains(text(),'Your invitation has been sent to')]/../span/i`,
    inviteToGroupAlreadyMemberOfThisGroupMessage: `//span[contains(text(),'is already a member of this group.')]`,
    inviteToGroupAlreadyMemberOfThisGroupMessageCrossIcon: `//span[contains(text(),'is already a member of this group.')]/../span/i`,
    inviteToGroupTeammateSuggestion: `//li[@class='suggestion-item selected']`,
    inviteToGroupTeammateSuggestionDuringGroupCreation: `//ul/li[@class='suggestion-item']`,
    inviteTeammatesToGroupInputLinkDuringGroupCreation: `//form[@name='invitePeople']//div[@class='tags']`,
    inviteTeammatesToGroupInputFieldDuringGroupCreation: `//form[@name='invitePeople']//div[@class='tags']/input`,
    crossIconOninvitationSentModalForInviteUsersInGroup: `//span[@class='cross']`,
    enterAdminMode: `//span[contains(text(),'Enter admin mode')]`,
    exitAdminMode:`//div[contains(text(),'Exit admin mode')]`,
    groupsDirectory: `//span/a[contains(text(),'Groups Directory')]`,
    searchForGroups:`//input[@placeholder='Search for groups']`,
    receipientsMustAckLabel: `//span[contains(text(),'Recipients must acknowledge to view the post')]`,
    publishPost: `(//button[contains(text(),"Publish")])[1]`,
    customizeUserProfilesTab: `//li[text()='Customize user profiles']`,
    customProfilesInfoText: `//div[@class='info-text' and contains(text(),'Hover over the fields and click Lock icon')]`,
    firstNameLockedField: `//div[contains(@class,'permanent')]//input[@name='First name' and @readonly='readOnly']`,
    lastNameLockedField: `//div[contains(@class,'permanent')]//input[@name='Last name' and @readonly='readOnly']`,
    positionLockedField: `//div[contains(@class,'permanent')]//input[@name='Position' and @readonly='readOnly']`,
    shortBioLockedField: `//div[contains(@class,'permanent')]//input[@name='Short bio' and @readonly='readOnly']`,
    locationLockedField: `//div[contains(@class,'permanent')]//input[@name='Location' and @readonly='readOnly']`,
    phoneLockedField: `//div[contains(@class,'permanent')]//input[@name='Phone' and @readonly='readOnly']`,
    linkedInLockedField: `//div[contains(@class,'permanent')]//input[@name='LinkedIn' and @readonly='readOnly']`,
    twitterLockedField: `//div[contains(@class,'permanent')]//input[@name='Twitter' and @readonly='readOnly']`,
    customFieldsInputField: `//input[contains(@class,'ng-empty') and @placeholder='Enter field name']`,
    fieldNameShortErrorMessage: `//span[text()='FIELD NAME TOO SHORT']`,
    fieldNameLongErrorMessage: `//span[text()='FIELD NAME TOO LONG']`,
    customFieldsAddButton: `//div[@class='form-group half']//input[contains(@class,'ng-touched')]/../../i[@class='action-btn add']`,
    fieldNameAlreadyExistsErrorMessage: `//span[text()='FIELD NAME ALREADY EXISTS!']`,
    customFieldsInputFieldWithErrorMessage: `//div[@class='form-group half has-error']//input`,
    additionalInfoTab: `//form[@name='updateDetails']//li[text()='Additional Info']`,
    manageContentLinkInNetworkSettings: `//li/a[text()='Manage content']`,
    contentPreferencesTab: `//li[text()='Content preferences']`,
    manageAcknowledgePostCreatorsHeading: `//div[@class='manage-ack-post-creators-div']//h4[text()='Manage Acknowledgement Post Creators']`,
    allowOnlySpecificMembersCheckbox: `//div[@class='manage-ack-post-creators-div']//span[text()='Allow only specific members to create acknowledgement type posts']/..//label`,
    acknowledgePostCreatorAddButton: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//li[@id='groupHeader']//span[contains(@class,'header-img add')]`,
    acknowledgePostCreatorInputField: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//input[contains(@class,'add-members-search-field')]`,
    removeUsersButtonInManageAcknowledgementPostCreators: `//div[@class='manage-ack-post-creators-div']//div[@id='removeUsersBtn' or text()='Remove Users']`,
    acknowledgePostCreatorsHeadingDisabled: `//div[@class='manage-ack-post-creators-div']//ul[contains(@class,'disableInteraction')]//span[text()='Acknowledgement Post Creators']`,
    acknowledgePostCreatorsUsersListDisabled: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList disableInteraction']`,
    acknowledgePostCreatorsHeading: `//div[@class='manage-ack-post-creators-div']//span[text()='Acknowledgement Post Creators']`,
    acknowledgePostCreatorsUserNameField: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//li[@id='groupHeader']//span[text()='Username']`,
    acknowledgePostCreatorsPositionField: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//li[@id='groupHeader']//span[text()='Position']`,
    acknowledgePostCreatorsEmailField: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//li[@id='groupHeader']//span[text()='Email']`,
    acknowledgePostCreatorsPhoneNoField: `//div[@class='manage-ack-post-creators-div']//ul[@class='usersList']//li[@id='groupHeader']//span[text()='Phone No.']`,
    acknowledgePostCreatorsSearchListInputField: `//div[@class='manage-ack-post-creators-div']//input[@id='searchUser']`,
    trendingHeading: `//div[@class='trending-tags-section']//p[text()='TRENDING:']`,
    trendingHashtagFilterDropdown: `//div[@class='trending-tags-section']//div[@class='trending-filter-container']//i[contains(@class,'lightgray')]`,
    trendingHashtagFilterThisMonth: `//div[@class='trending-tags-section']//ul[@class='trending-filter-lists']//li[text()='This month']`,
    trendingHashtagFilterThisWeek: `//div[@class='trending-tags-section']//ul[@class='trending-filter-lists']//li[text()='This week']`,
    trendingHashtagFilterToday: `//div[@class='trending-tags-section']//ul[@class='trending-filter-lists']//li[text()='Today']`,
    firstTrendingHashtagName: `(//div[@class='tag-info']/p)[1]`,
    firstTrendingHashtagPostsCount: `(//div[@class='tag-info']/p)[1]/../p[@class='tag-posts-number']`,
    manageGroupsLinkInNetworkSettings: `//li/a[text()='Manage Groups']`,
    allowOnlySpecificMembersToCreateGroupsCheckbox: `//div[@class='settings-manage-groups-wrapper']//span[text()='Allow only specific members to create groups']/..//label`,
    groupsHeading: `//div[@class='heading']//span[text()='Groups']`,
    groupCreatorsAddButton: `//div[@class='settings-manage-groups-wrapper']//ul[@class='usersList']//li[@id='groupHeader']//span[contains(@class,'header-img add')]`,
    groupCreatorsInputField: `//div[@class='settings-manage-groups-wrapper']//ul[@class='usersList']//input[contains(@class,'add-members-search-field')]`,
    removeUsersButtonInManageGroups: `//div[@class='settings-manage-groups-wrapper']//div[@id='removeUsersBtn' or text()='Remove Users']`,
    teamDirectorySearchForPeopleInputField: `//input[@placeholder='Search for people']`,
    removeFromNetwork: `//span[text()='Remove from network']`,
    leaveNetworkButton: `//button[text()='Leave Network']`,
    shareWithOthers: `//span[contains(text(),'Share with others')]`,
    unblockButton: `//span[contains(text(),'Unblock')]`,
    groupMembers: `//a[contains(text(),'Member')]`,
    disabledUsersList: `//ul[@class='usersList disableInteraction']`,
    chatClose: `//div[2]/div[@class='namesPopover']`,
    typeSomethingHere: `//div[@class='cnv-onboarding-add-comment-tooltip']//span[text()='Type something here']`,
    selectingSomeText: `//div[@class='comment_txt']//mark[text()="selecting some text"]`,
    commentOnThis: `//div[contains(@class,'sel-open-comments')]//span[text()='Comment on this']`,
    typeGotIt: `//div[@class='cnv-onboarding-add-comment-tooltip annotation']//span[text()='Type "got it" to finish your reply']`,
    taskCompletion1Percent: `//div[@class='cnv-progress-bar']//div[@class='green']/../span[@class='count' and text()='1%']`,
    learnaboutfeedStriked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='1. Learn about feed' and @class='strike-through']`,
    learAboutFeedChecked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='1. Learn about feed' and @class='strike-through']//i[contains(@class,'glyphicon-ok')]`,
    createAGroup: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Create a group']`,
    createaNewGroupButton: `//div[contains(@class,'onboardingToolTips')]//a[text()='Create a new group']`,
    createaGroupStriked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Create a group' and @class='strike-through']`,
    createaGroupChecked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Create a group' and @class='strike-through']//i[contains(@class,'glyphicon-ok')]`,
    taskCompletion40Percent: `//div[@class='cnv-progress-bar']//div[@class='green']/../span[@class='count' and text()='40%']`,
    taskCompletion20Percent: `//div[@class='cnv-progress-bar']//div[@class='green']/../span[@class='count' and text()='20%']`,
    shareaPost: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='3. Share a post']`,
    letsDoThisButton: `//div[contains(@class,'onboardingToolTips')]//a[text()="Let's do this!"]`,
    shareThisPost: `//button[text()='Share this post']`,
    gettingStarted: `//cnv-feed-item//a[text()='#GettingStarted']`,
    shareaPostStriked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='3. Share a post' and @class='strike-through']`,
    shareaPostChecked: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='3. Share a post' and @class='strike-through']//i[contains(@class,'glyphicon-ok')]`,
    taskCompletion60Percent: `//div[@class='cnv-progress-bar']//div[@class='green']/../span[@class='count' and text()='60%']`,
    addProfilePhotoButton: `//cnv-onboarding-tooltips//a[text()='Add a profile photo']`,
    navBarProfileImage: `//div[@class='row no-margin header-bar-container']//cnv-user-profile-image//img`,
    setUpanIntegrationButton: `//div[contains(@class,'onboardingToolTips')]//a[text()="Set up an integration"]`,
    manageIntegrations: `//span[contains(text(),'Manage integrations')]`,
    allIntegrations: `//a[contains(text(),'All Integrations')]`,
    twitterIntegrations: `//h3[contains(text(),'Twitter Integration')]`,
    change: `//a[contains(text(),'change')]`,
    connectToTwiiterAccount: `//button[contains(text(),'Connect to Twitter account')]`,
    twitterUserName: `//input[@id='username_or_email']`,
    twitterPassword: `//input[@id='password']`,
    authorizeApp: `//input[@value='Authorize app' or @value='Authorise app']`,
    labelGetTweets: `//span[text()='Get tweets by this user']/../label`,
    getTweets: `//input[@name='twitter_handles']`,
    addNewGroup: `//div[@class='add-webhook-integration add-twitter-integration']//div/a[contains(text(),'create a new group')]`,
    privateGroupIntegration: `//div[@class='group-create-type']//div/div/div[contains(text(),'Private')]`,
    nextButtonIntegration: `//button[contains(text(),'Next')]`,
    groupName: `//div[@class='form-group']/input[@placeholder='e.g Marketing']`,
    createGroupNextButton: `//*[@id="crtGrpNxtBtn"]`,
    createPrivateGroup: `//button[contains(text(),'Create group')]`,
    integrationNameForTwitter: `//div[@class='add-webhook-integration add-twitter-integration']//div[@class='field-item-right']/input[@placeholder='What name should this post appear from?']`,
    saveButtonForTwitter: `//div[@class='add-webhook-integration add-twitter-integration']//button[contains(text(),'Save')]`,
    divPostEditor: `//div[@aria-label='Tweet text']`,
    tweetButton: `//div[@data-testid='toolBar']//span[text()='Tweet']`,
    removeThisIntegration: `//span[text()='Remove this integration']`,
    buttonOk: `//button[text()='Ok']`,
    integrationDeletedAlert: `//span[text()='Integration deleted']`,
    createGroupInDirectory: `//button[contains(text(),'Create Group')]`,
    grpSearch: `//div[@class='header-section']//input[@class='form-control']`,
    members: `//div[@class='app-sub-header']//a[contains(text(),'Member')]`,
    makeAdminButton: `//div[@class='modal-footer']/button[contains(text(),'Make admin')]`,
    settings: `//div[@class='app-sub-header']/a[contains(text(),'Settings')]`,
    publicGroup: `//div[@class='setting-controls']/div[@class='groupType']/div/div[contains(text(),'Public')]`,
    privateGroupSettings: `//div[@class='setting-controls']/div[@class='groupType']/div/div[contains(text(),'Private')]`,
    makeAdmin: `//a[@class='menu-item-wrapper']/span[contains(text(),'Make group admin')]`,
    groupNameSettings: `//div[@class='setting-controls']/input`,
    seeMorePublic: `//li[@bo-show='publicGroupsCollapsed && publicGroupsArray && publicGroupsArray.length > 5']/a`,
    deleteGroupSettings: `//div[@class='settings-footer']//a[@class='pull-left' and contains(text(),'Delete group')]`,
    deleteButtonSettings: `//div[@class='modal-footer']/button[contains(text(),'Delete')]`,
    whatsNew: `//div[@class='row no-margin whatsnew menu-items-container']//a[contains(text(),'What')]`,
    loginButtonForTwitter: `//a[@data-testid='loginButton']`,
    passwordInputFieldForTwitter: `//input[@type='password']`,
    twitterLoginButton: `(//div[@data-testid='LoginForm_Login_Button']//span[contains(text(),'Log in')])[1]`,
    keepAccountSafe: `//div[@class='PageHeader Edge' and contains(text(),'Help us keep your account safe.')]`,
    textFieldForPhoneNo: `//input[@class='Form-textbox Edge-textbox']`,
    submit: `//input[@value='Submit']`,
    shareaPostPk: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Share a post']`,
    shareaPostStrikedPk: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Share a post' and @class='strike-through']`,
    shareaPostCheckedPk: `//div[@id='homeAppCont']//div[@class='checklist-wrapper']//ul[@class='onboarding-checklist']//a[normalize-space()='2. Share a post' and @class='strike-through']//i[contains(@class,'glyphicon-ok')]`,
    usersListInGroup: `//div[@class='user-master-list']`,
    copyPostlink: `(//a[contains(text(),'Copy link')])[1]`,
    postLink: `//div[@class='ql-editor scroll-enabled']//a[@href]`,
    tooltipUrl: `//div[@class='ql-tooltip ql-link-tooltip']/a[@class='url']`,
    searchForPeopleInputField: `//input[@placeholder='Search for people']`,
    progressLine: `//div[@class='progress-line']`,
    imapIntegrations: `//h3[contains(text(),'IMAP Integration')]`,
    selectDropdown: `//select[@name='email_provider']`,
    searchforIntegrations: `(//input[@placeholder='Search for integrations'])[2]`,
    yahooOption: `//option[@label='Yahoo']`,
    emailAddress: `//input[@name='email_address']`,
    userOption: `//span[@role='presentation']`,
    accountInfo: `//a[contains(text(),'Account Info')]`,
    accountSecurityForYahoo: `//span[contains(text(),'Account Security')]`,
    moreConvo: `//div[@class='settings-app-password']`,
    selectApp: `//select[@name='selectedApp']`,
    otherApp: `//option[@value='Other']`,
    customValue: `//input[@id='txtApName']`,
    generate: `//button[contains(text(),'Generate')]`,
    getPassword: `//div[@class='tcv-code-txt medium-animated fadeIn']`,
    doneButton: `//button[contains(text(),'Done')]`,
    closeCross: `//a[@class='close']`,
    passwordImap: `//input[@name='password']`,
    authenticateButton: `(//button[contains(text(),'Authenticate')])[1]`,
    okButton: `//button[contains(text(),'OK')]`,
    addGroup: `//div[@class='add-webhook-integration imap-integration-styles']//div/a[contains(text(),'create a new group')]`,
    authenticate: `(//button[contains(text(),'Authenticate')])[2]`,
    enableReply: `//label[@for='enableReplySmtp']`,
    integrationNameForImap: `//div[@class='add-webhook-integration imap-integration-styles']//div[@class='field-item-right']/input[@placeholder='What name should this post appear from?']`,
    saveButtonForImap: `//div[@class='add-webhook-integration imap-integration-styles']//button[contains(text(),'Save')]`,
    getCompanyInviteLink: `//div[@class='feed-right-panel-wrapper']//div[@class='vanity-help-txt']/span[contains(text(),'Get your company')]`,
    backToIntegrations: `//div[@class='add-webhook-integration imap-integration-styles']//a[contains(text(),'Back to Integrations')]`,
    configuredIntegrations: `//a[contains(text(),'Configured Integrations')]`,
    managePostPermissionsHeading: `//h4[contains(text(),'Manage Post Permissions')]`,
    permanentFieldsHeading: `//div[@class='header' and contains(text(),'Permanent fields')]`,
    composeButtonGuerrialMail: `//a[@title='Compose']`,
    toInputFieldGuerrilaMail: `//input[@class='form-field outline' and @name='to']`,
    subjectGuerrilaMail: `//input[@class='form-field outline' and @name='subject']`,
    bodyGuerrilaMail: `//textarea[@class='form-field outline' and @name='body']`,
    sendButtonGuerrilaMail: `//input[@name='send']`,
    recaptchaCheckbox: `//div[@class='recaptcha-checkbox-border']`,
    generateAppPasswords: `//a[@class='mc-action link-generate-ap']`,
    getStarted: `//button[contains(text(),'Get')]`,
    deleteButtoninImapYahoo: `//button[contains(text(),'Delete')]`,
    accessandSecurity: `//h1[contains(text(),'Access')]`,
    cancelButtonInYahoo: `//input[@value='Cancel']`,
    
  
  
  }